" Use Vim settings instead of Vi
set nocompatible

" General settings
syntax on
filetype on
filetype plugin on
filetype indent on
colorscheme slate
set scrolloff=999
set title
set laststatus=2
set viminfo+=n~/.vim/.viminfo
set autoread
set wildmenu

" Gutter settings
set number
set numberwidth=5

" Line formatting
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set nowrap

" Search settings
set ignorecase
set smartcase
set hlsearch
set incsearch

" Status bar settings
let g:currentmode={
       \ 'n'  : 'NORMAL ',
       \ 'v'  : 'VISUAL ',
       \ 'V'  : 'V·Line ',
       \ "\<C-V>" : 'V·Block ',
       \ 'i'  : 'INSERT ',
       \ 'R'  : 'R ',
       \ 'Rv' : 'V·Replace ',
       \ 'c'  : 'Command ',
       \}
set statusline=
set statusline+=\ %{toupper(g:currentmode[mode()])} "vim mode
set statusline+=%F                                  "file path
set statusline+=%{&modified?'[+]':''}               "modified flag
set statusline+=%=\ %l/%L\,\ %c                     "line num/total, column num
