set number
set numberwidth=4
set shiftwidth=4
set autoindent
set expandtab
set scrolloff=5
set nowrap
set smartcase
set showmode
set ignorecase
set hlsearch
set incsearch
set title
set laststatus=2
set viminfo+=n~/.vim/.viminfo

syntax on
colorscheme murphy

let g:currentmode={
       \ 'n'  : 'NORMAL ',
       \ 'v'  : 'VISUAL ',
       \ 'V'  : 'V·Line ',
       \ "\<C-V>" : 'V·Block ',
       \ 'i'  : 'INSERT ',
       \ 'R'  : 'R ',
       \ 'Rv' : 'V·Replace ',
       \ 'c'  : 'Command ',
       \}

set statusline=
set statusline+=\ %{toupper(g:currentmode[mode()])} "vim mode
set statusline+=%F                                  "file path
set statusline+=%{&modified?'[+]':''}               "modified flag
set statusline+=%=\ %l/%L                           "line number/total

