export ZSH="$HOME/.oh-my-zsh"
export ZSH_COMPDUMP=$HOME/.cache/.zcompdump-$HOST
export LESSHISTFILE=$HOME/.cache/.lesshst

ZSH_THEME="robbyrussell"
plugins=(git)

HISTFILE=$HOME/.cache/.zsh_history

source $ZSH/oh-my-zsh.sh

alias c="xclip"
alias v="xclip -o"
alias cs="xclip -selection clipboard"
alias vs="xclip -o -selection clipboard"
alias cp="cp -iv"
alias mv="mv -iv"
alias src="source ~/.zshrc && echo \"~/.zshrc reloaded\""
alias editrc="vim ~/.zshrc"
alias dotfiles="cd ~/.dotfiles"
alias dotfile="cd ~/.dotfiles"
alias v="vim"
alias clr="clear"
alias sys="systemctl"
