export ZSH="$HOME/.oh-my-zsh"
export ZSH_COMPDUMP=$HOME/.cache/.zcompdump-$HOST
export LESSHISTFILE=$HOME/.cache/.lesshst
export HISTFILE=$HOME/.cache/.zsh_history

ZSH_THEME="robbyrussell"
plugins=(git)

source $ZSH/oh-my-zsh.sh

function mkbak() {
  cp $1 $1.bak
}

alias c="xclip"
alias v="xclip -o"
alias cs="xclip -selection clipboard"
alias vs="xclip -o -selection clipboard"
alias cp="cp -iv"
alias mv="mv -iv"
alias src="source ~/.zshrc && echo \"~/.zshrc reloaded\""
alias editrc="vim ~/.zshrc"
alias edt="editrc"
alias dotfiles="cd ~/.dotfiles"
alias dotfile="dotfiles"
alias v="vim"
alias clr="clear"
alias sys="systemctl"
